### ISSUE TITLE
Workspace thumbnails.

### ISSUE THREAD

**Issue by trusktr** [zakkak/workspace-grid-gnome-shell-extension#14] opened 2015-09-11 06:29 UTC
Hi, I'm wondering if you might know how to add the workspace thumbnails to the live switch indicator?

For example, how would we add the workspace thumbnails to the following instead of the blank squares?

![screenshot_275_1](https://cloud.githubusercontent.com/assets/297678/9808371/4f8a461a-5813-11e5-80a1-7ce6e06e50d2.png)

That's an old screenshot, but you know that thing I'm talking about. The squares are empty and boring. xD I'd like them to have thumbnails like what the overview's right sidebar has:

![ubuntugnome](https://cloud.githubusercontent.com/assets/297678/9808432/bc65cab6-5813-11e5-8f45-d668b02b5b32.png)

**Comment by zakkak** [comment] 2015-09-11 08:43
Duplicate of #4 ?

**Closed** 2015-11-29 13:13 UTC
