### ISSUE TITLE
Honour 'Dynamic' setting

### ISSUE THREAD

**Issue by i90rr** [zakkak/workspace-grid-gnome-shell-extension#17] opened 2015-11-29 00:40 UTC
Hi, the extension works great when defining Static workspaces, it would be great if it works also with Dynamic workspaces.

**Comment by zakkak** [comment] 2015-11-29 13:08
How would you define the layout in the case of dynamic workspaces?
Setting the maximum number of workspaces per row, so that a new row would be created after X workspaces?
Setting the maximum number of workspaces per col, so that a new col would be created after X workspaces?

**Comment by zakkak** [comment] 2015-11-29 13:27
Is this a duplicate of #11?

**Comment by zakkak** [comment] 2017-01-27 23:45
Closing this due to inactivity

**Closed by zakkak** 2017-01-27 23:45 UTC
